import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Work", description: "Client work, Meleph products and clearly labelled demonstrations." };
const projects = [
  { type: "Demonstration", title: "Real Estate AI Customer Agent", text: "An illustrative workflow showing property enquiries, captured requirements and a contextual handoff to an agent.", href: null, visual: "property" },
  { type: "Demonstration", title: "Aviation Enquiry System", text: "An illustrative workflow showing route questions, enquiry context and a structured next action for the team.", href: null, visual: "aviation" },
  { type: "Meleph Product", title: "LeKiray", text: "A digital product developed and operated by Meleph.", href: "/products/lekiray", visual: "lekiray" },
] as const;

export default function WorkPage() { return <><section className="page-hero-grid relative overflow-hidden border-b border-ink/10 py-24 md:py-32"><div className="page-glow absolute inset-y-0 right-0 w-1/2" /><div className="container-site relative grid gap-10 lg:grid-cols-[1fr_.6fr] lg:items-end"><div><p className="eyebrow">Work / Demonstrations / Products</p><h1 className="mt-7 max-w-5xl font-serif text-[clamp(3.5rem,7vw,7rem)] leading-[.9] tracking-[-.045em] text-ink">Systems and products made tangible.</h1></div><p className="border-l border-gold/50 pl-6 text-sm leading-7 text-ink/55">Demonstrations show what a system could do. They are clearly separated from deployed client work and Meleph-owned products.</p></div></section><section className="container-site py-20 md:py-28"><div className="space-y-8">{projects.map((project, index) => { const content = <div className="grid min-h-[32rem] lg:grid-cols-[.72fr_1.28fr]"><div className="flex flex-col p-7 md:p-10"><div className="flex items-center justify-between"><span className="text-[.52rem] uppercase tracking-[.18em] text-gold">{project.type}</span><span className="font-mono text-[.5rem] text-ink/25">0{index + 1} / 03</span></div><h2 className="mt-20 font-serif text-4xl leading-tight text-ink md:text-5xl">{project.title}</h2><p className="mt-6 max-w-md text-sm leading-7 text-ink/52">{project.text}</p>{project.href ? <span className="mt-auto pt-10 text-sm text-ink">View product →</span> : <span className="mt-auto pt-10 text-[.5rem] uppercase tracking-[.15em] text-ink/35">Illustrative system study</span>}</div><ProjectVisual type={project.visual} /></div>; return project.href ? <Link key={project.title} href={project.href} className="group block overflow-hidden border border-ink/12 transition-shadow hover:shadow-[0_24px_60px_rgba(13,27,42,.12)]">{content}</Link> : <article key={project.title} className="overflow-hidden border border-ink/12">{content}</article>; })}</div><div className="mt-24 grid gap-8 border-t border-ink/12 pt-10 md:grid-cols-2"><div><p className="eyebrow">Client work</p><h2 className="mt-5 font-serif text-4xl text-ink">Shared when it can be shared well.</h2></div><p className="max-w-xl text-sm leading-7 text-ink/52">Client work will appear here when it can be presented accurately and with permission.</p></div></section></>; }

function ProjectVisual({ type }: { type: "property" | "aviation" | "lekiray" }) {
  if (type === "property") return <div className="relative min-h-[26rem] overflow-hidden bg-brand-stone/45 p-7"><div className="absolute inset-0 page-hero-grid opacity-50" /><div className="relative ml-auto max-w-md border border-ink/15 bg-ivory p-4 shadow-[0_24px_55px_rgba(13,27,42,.14)]"><div className="flex justify-between border-b border-ink/10 pb-3 text-[.46rem] uppercase tracking-wider text-ink/35"><span>Property enquiry</span><span>Active</span></div><div className="mt-4 border border-ink/10 bg-white p-3 text-[.53rem] leading-5 text-ink/55">I&apos;m looking for a three-bedroom property close to the city, ideally with outdoor space.</div><div className="ml-8 mt-3 bg-ink p-3 text-[.53rem] leading-5 text-white/70">I can help narrow that down. Is there a preferred area or budget range?</div><div className="mt-5 grid grid-cols-2 gap-2"><VisualField label="Intent" value="Property search" /><VisualField label="Next step" value="Agent handoff" /><VisualField label="Bedrooms" value="3" /><VisualField label="Preference" value="Outdoor space" /></div></div></div>;
  if (type === "aviation") return <div className="relative min-h-[26rem] overflow-hidden bg-[#d9e0df] p-7"><div className="absolute left-0 right-0 top-1/2 h-px bg-ink/10" /><div className="relative grid h-full place-items-center"><div className="w-full max-w-lg border border-ink/15 bg-[#f8f6f0] shadow-[0_24px_55px_rgba(13,27,42,.14)]"><div className="flex items-center justify-between bg-ink px-4 py-3 text-[.5rem] uppercase tracking-wider text-white/55"><span>Flight enquiry</span><span className="text-gold">Routing</span></div><div className="grid grid-cols-[1fr_auto_1fr] items-center p-6 text-center"><div><p className="font-serif text-4xl text-ink">DXB</p><p className="text-[.45rem] text-ink/35">Origin</p></div><div className="px-5"><span className="block text-gold">✦</span><span className="mt-2 block w-20 border-t border-dashed border-ink/20" /></div><div><p className="font-serif text-4xl text-ink">LHR</p><p className="text-[.45rem] text-ink/35">Destination</p></div></div><div className="grid grid-cols-3 border-t border-ink/10 p-4"><VisualField label="Passengers" value="4" /><VisualField label="Timing" value="Flexible" /><VisualField label="Action" value="Review" /></div></div></div></div>;
  return <div className="relative min-h-[26rem] overflow-hidden bg-ink p-7 text-white"><div className="technical-grid-dark absolute inset-0 opacity-40" /><div className="relative flex h-full flex-col border border-white/12 p-7"><div className="flex justify-between text-[.48rem] uppercase tracking-[.18em] text-white/30"><span>Meleph product 01</span><span>In development</span></div><span className="my-auto font-serif text-[clamp(5rem,10vw,9rem)] tracking-[-.06em] text-ivory">LeKiray</span><div className="flex items-end justify-between border-t border-white/10 pt-4"><span className="text-[.5rem] uppercase tracking-wider text-gold">Digital product</span><span className="font-serif text-3xl text-gold">L</span></div></div></div>;
}

function VisualField({ label, value }: { label: string; value: string }) { return <div className="p-2"><p className="text-[.42rem] uppercase tracking-wider text-ink/30">{label}</p><p className="mt-1 text-[.52rem] font-medium text-ink">{value}</p></div>; }
