"use client";

import Link from "next/link";
import { useState } from "react";

const navigation = [{ label: "Products", href: "/products" }, { label: "Work", href: "/work" }, { label: "About", href: "/about" }] as const;
const solutions = [{ label: "AI Customer Agent", href: "/solutions/ai-customer-agent" }, { label: "Custom AI Systems", href: "/solutions/custom-ai-systems" }] as const;

export function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="fixed inset-x-0 top-0 z-50 bg-ivory/95 backdrop-blur-lg"><nav className="container-site flex h-[72px] items-center" aria-label="Primary navigation"><Link href="/" className="font-serif text-[1.7rem] font-semibold tracking-[-.04em] text-ink">Meleph</Link><div className="ml-auto hidden items-center gap-9 md:flex"><div className="group relative py-6"><Link href="/solutions" className="text-sm text-ink/65 transition-colors hover:text-ink">Solutions <span className="ml-1 text-ink/35">⌄</span></Link><div className="invisible absolute left-1/2 top-16 w-64 -translate-x-1/2 rounded-xl bg-white p-2 opacity-0 shadow-[0_18px_55px_rgba(13,27,42,.13)] transition-all group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100">{solutions.map(item => <Link key={item.href} href={item.href} className="block rounded-lg px-4 py-3 text-sm text-ink/65 hover:bg-ivory hover:text-ink">{item.label}</Link>)}</div></div>{navigation.map(item => <Link key={item.href} href={item.href} className="text-sm text-ink/65 transition-colors hover:text-ink">{item.label}</Link>)}<Link href="/get-started" className="rounded-full bg-ink px-5 py-2.5 text-sm font-medium text-ivory transition-transform hover:-translate-y-0.5">Get Started <span className="ml-1">→</span></Link></div><button type="button" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(value => !value)} className="ml-auto grid size-10 place-items-center md:hidden"><span className="space-y-1.5"><i className={`block h-px w-5 bg-ink transition-transform ${open ? "translate-y-[3.5px] rotate-45" : ""}`} /><i className={`block h-px w-5 bg-ink transition-transform ${open ? "-translate-y-[3.5px] -rotate-45" : ""}`} /></span></button></nav>{open ? <div className="bg-ivory px-6 pb-7 md:hidden"><Link href="/solutions" onClick={() => setOpen(false)} className="block py-3 text-lg font-medium text-ink">Solutions</Link>{solutions.map(item => <Link key={item.href} href={item.href} onClick={() => setOpen(false)} className="block py-2 pl-4 text-sm text-ink/60">{item.label}</Link>)}{navigation.map(item => <Link key={item.href} href={item.href} onClick={() => setOpen(false)} className="block py-3 text-lg font-medium text-ink">{item.label}</Link>)}<Link href="/get-started" onClick={() => setOpen(false)} className="mt-4 flex justify-between rounded-xl bg-ink px-5 py-4 text-sm text-ivory">Get Started <span>→</span></Link></div> : null}</header>;
}
