import Link from "next/link";
import { CustomerAgentSurface, WorkflowSurface } from "@/components/home/ProductSurfaces";

const workflow = ["Understand", "Answer", "Capture", "Act", "Connect", "Follow up"];
const capabilityGroups = [
  { title: "Engage customers", items: "Customer conversations · Connected channels · Proactive messaging", visual: "messages" },
  { title: "Capture opportunity", items: "Lead capture · Intent · Requirements · Contact details", visual: "capture" },
  { title: "Move work forward", items: "Appointments · Quotations · Next actions", visual: "actions" },
  { title: "Connect the team", items: "Conversation inbox · Human handoff · Workflows & integrations", visual: "team" },
] as const;

export function Homepage() {
  return <>
    <section className="home-hero overflow-hidden pb-20 pt-16 md:pb-28 md:pt-24"><div className="home-container grid items-center gap-14 lg:grid-cols-12"><div className="lg:col-span-5"><p className="home-eyebrow home-reveal">AI Systems &amp; Digital Products</p><h1 className="home-reveal home-delay-1 mt-6 text-[clamp(3.2rem,5.4vw,5.9rem)] font-semibold leading-[.98] tracking-[-.055em] text-ink">Give your business a system that listens, understands and acts.</h1><p className="home-reveal home-delay-2 mt-8 max-w-xl text-base leading-8 text-ink/60 md:text-lg">Meleph builds AI systems and digital products that help businesses understand customer needs, capture opportunities, connect teams and move every interaction toward the right next step.</p><div className="home-reveal home-delay-3 mt-9 flex flex-wrap items-center gap-5"><Link href="/solutions/ai-customer-agent" className="home-primary">Explore the AI Customer Agent <span>→</span></Link><Link href="/get-started" className="home-secondary">Talk to us</Link></div></div><div className="home-reveal home-delay-2 lg:col-span-7 lg:translate-x-8 xl:translate-x-16"><CustomerAgentSurface /></div></div></section>

    <section className="home-section bg-white"><div className="home-container"><div className="grid gap-10 lg:grid-cols-12 lg:items-end"><div className="lg:col-span-5"><p className="home-eyebrow">AI Customer Agent</p><h2 className="home-heading mt-5">From conversation to action.</h2></div><p className="max-w-xl text-base leading-8 text-ink/55 lg:col-span-5 lg:col-start-8">A single system carries context through the entire interaction—from understanding the first question to following up on the next step.</p></div><div className="mt-16 overflow-hidden rounded-3xl bg-[#f2efe8] p-6 md:p-10"><div className="mx-auto max-w-5xl"><div className="relative flex flex-col gap-4 md:flex-row md:items-center md:justify-between md:gap-0"><div className="absolute left-[8%] right-[8%] top-5 hidden h-0.5 bg-ink/10 md:block" />{workflow.map((item, index) => <div key={item} className="relative z-10 flex items-center gap-4 md:flex-col md:gap-3"><span className={`grid size-10 place-items-center rounded-full text-sm font-semibold ${index < 4 ? "bg-ink text-white" : "bg-white text-ink/45"}`}>{index < 3 ? "✓" : index + 1}</span><span className="text-sm font-medium text-ink">{item}</span></div>)}</div><div className="mt-12 grid gap-5 rounded-2xl bg-white p-5 shadow-sm md:grid-cols-[1fr_auto_1fr] md:items-center md:p-7"><div><p className="text-sm font-semibold text-ink">Customer need understood</p><p className="mt-2 text-sm text-ink/48">Enterprise package · Team of 75 · Inbound qualification</p></div><span className="hidden text-ink/25 md:block">→</span><div className="md:text-right"><p className="text-sm font-semibold text-ink">Consultation ready to schedule</p><p className="mt-2 text-sm text-ink/48">Assigned to Maya with full context</p></div></div></div></div></div></section>

    <section className="home-section"><div className="home-container"><div className="max-w-3xl"><p className="home-eyebrow">Capabilities</p><h2 className="home-heading mt-5">Everything needed to move a conversation forward.</h2><p className="mt-6 text-base leading-8 text-ink/55">Capabilities are grouped around the work they enable, rather than presented as disconnected features.</p></div><div className="mt-16 space-y-20">{capabilityGroups.map((group, index) => <div key={group.title} className="grid items-center gap-10 lg:grid-cols-12"><div className={`${index % 2 ? "lg:order-2 lg:col-start-8" : "lg:col-start-1"} lg:col-span-5`}><h3 className="text-3xl font-semibold tracking-[-.035em] text-ink md:text-4xl">{group.title}</h3><p className="mt-5 max-w-md text-base leading-8 text-ink/52">{group.items}</p></div><div className={`${index % 2 ? "lg:order-1 lg:col-start-1" : "lg:col-start-7"} lg:col-span-6`}><CapabilityVisual kind={group.visual} /></div></div>)}</div></div></section>

    <section className="home-section bg-ink text-white"><div className="home-container grid gap-14 lg:grid-cols-12 lg:items-center"><div className="lg:col-span-5"><p className="home-eyebrow text-white/50">Custom AI Systems</p><h2 className="home-heading mt-5 text-white">When the workflow does not fit a template.</h2><p className="mt-7 max-w-lg text-base leading-8 text-white/55">We design internal assistants, operational tools and connected workflows around the way the business actually needs to work.</p><Link href="/solutions/custom-ai-systems" className="mt-8 inline-flex items-center gap-2 text-sm font-medium text-white">Explore Custom AI Systems <span>→</span></Link></div><div className="lg:col-span-7"><WorkflowSurface /></div></div></section>

    <section className="home-section overflow-hidden"><div className="home-container"><div className="grid min-h-[620px] overflow-hidden rounded-3xl bg-[#e9e2d6] lg:grid-cols-12"><div className="flex flex-col justify-center p-8 md:p-14 lg:col-span-5"><p className="home-eyebrow">Digital Products</p><h2 className="mt-6 text-6xl font-semibold tracking-[-.06em] text-ink md:text-8xl">LeKiray</h2><p className="mt-7 max-w-md text-base leading-8 text-ink/55">A Meleph-owned digital product developed around a focused real-world need.</p><Link href="/products/lekiray" className="mt-9 inline-flex items-center gap-2 text-sm font-semibold text-ink">Discover LeKiray <span>→</span></Link></div><div className="relative min-h-[420px] overflow-hidden bg-ink lg:col-span-7"><div className="absolute -right-20 top-1/2 size-[520px] -translate-y-1/2 rounded-full bg-gold/80" /><div className="absolute left-12 top-12 rounded-2xl bg-white/10 px-5 py-4 text-sm text-white/70 backdrop-blur-sm">A focused digital product</div><span className="absolute bottom-5 left-5 text-[13rem] font-semibold leading-none tracking-[-.1em] text-white md:bottom-0 md:left-12 md:text-[20rem]">L</span></div></div></div></section>

    <section className="home-section bg-white"><div className="home-container"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="home-eyebrow">Work</p><h2 className="home-heading mt-5">Built to make the system clear.</h2></div><Link href="/work" className="text-sm font-medium text-ink">View all work →</Link></div><div className="mt-14 grid gap-6 lg:grid-cols-2"><WorkPreview type="property" title="Real Estate AI Customer Agent" label="Demonstration" /><WorkPreview type="aviation" title="Aviation Enquiry System" label="Demonstration" /><div className="lg:col-span-2"><WorkPreview type="lekiray" title="LeKiray" label="Meleph Product" wide /></div></div></div></section>

    <section className="home-section"><div className="home-container"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-4"><p className="home-eyebrow">How we work</p><h2 className="home-heading mt-5">Understand first. Build second.</h2></div><div className="grid gap-x-8 gap-y-10 sm:grid-cols-2 lg:col-span-7 lg:col-start-6 lg:grid-cols-3">{["Understand", "Define", "Design", "Build", "Launch", "Improve"].map((step, index) => <div key={step}><span className="text-sm text-ink/30">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-4 text-lg font-semibold text-ink">{step}</h3></div>)}</div></div></div></section>

    <section className="px-5 pb-5"><div className="home-container rounded-3xl bg-ink py-20 text-center text-white md:py-28"><h2 className="mx-auto max-w-4xl text-[clamp(2.7rem,5vw,5rem)] font-semibold leading-[1.02] tracking-[-.05em]">Have a process that should work better?</h2><div className="mt-9 flex flex-wrap justify-center gap-4"><Link href="/get-started?path=project" className="rounded-full bg-white px-6 py-3.5 text-sm font-semibold text-ink">Discuss a Project</Link><Link href="/get-started?path=demo" className="rounded-full bg-white/10 px-6 py-3.5 text-sm font-semibold text-white">Request a Demo</Link></div></div></section>
  </>;
}

function CapabilityVisual({ kind }: { kind: string }) { const content = kind === "messages" ? ["Can you help me choose the right package?", "Yes. I can ask a few questions and guide you."] : kind === "capture" ? ["Intent", "Enterprise enquiry", "Team size", "50–100"] : kind === "actions" ? ["Next action", "Schedule consultation", "Assigned", "Maya Chen"] : ["Inbox", "Team handoff", "CRM", "Connected"]; return <div className="min-h-[340px] rounded-3xl bg-[#efebe3] p-6 md:p-9"><div className="h-full min-h-[268px] rounded-2xl bg-white p-5 shadow-sm">{kind === "messages" ? <div className="flex h-full flex-col justify-center gap-4"><div className="max-w-[80%] rounded-2xl rounded-bl-sm bg-[#f1eee8] p-4 text-sm text-ink/65">{content[0]}</div><div className="ml-auto max-w-[82%] rounded-2xl rounded-br-sm bg-ink p-4 text-sm text-white/85">{content[1]}</div></div> : <div className="grid h-full content-center gap-4 sm:grid-cols-2">{content.map((item, index) => index % 2 === 0 ? <div key={item} className="rounded-xl bg-[#f5f3ee] p-4"><p className="text-xs text-ink/40">{item}</p><p className="mt-4 text-base font-semibold text-ink">{content[index + 1]}</p></div> : null)}</div>}</div></div>; }

function WorkPreview({ type, title, label, wide = false }: { type: string; title: string; label: string; wide?: boolean }) { return <Link href={type === "lekiray" ? "/products/lekiray" : "/work"} className={`group overflow-hidden rounded-3xl bg-[#f0ede6] ${wide ? "grid md:grid-cols-2" : "block"}`}><div className="relative min-h-[360px] overflow-hidden p-7">{type === "property" ? <div className="absolute inset-8 rounded-2xl bg-white p-5 shadow-lg"><p className="text-sm font-semibold text-ink">Property enquiry</p><div className="mt-10 rounded-xl bg-[#f2efe8] p-4 text-sm text-ink/60">Three bedrooms, close to the city, with outdoor space.</div><div className="ml-auto mt-3 w-4/5 rounded-xl bg-ink p-4 text-sm text-white/80">I can narrow that down and connect you with an agent.</div></div> : type === "aviation" ? <div className="absolute inset-8 flex flex-col justify-center rounded-2xl bg-ink p-8 text-white shadow-lg"><div className="flex items-center justify-between"><span className="text-4xl font-semibold">DXB</span><span className="h-px flex-1 bg-white/20 mx-6" /><span className="text-4xl font-semibold">LHR</span></div><p className="mt-10 text-sm text-white/45">Enquiry captured · Requirements ready for review</p></div> : <><div className="absolute inset-0 bg-ink" /><div className="absolute -right-16 top-1/2 size-96 -translate-y-1/2 rounded-full bg-gold" /><span className="absolute bottom-0 left-8 text-[12rem] font-semibold leading-none text-white">L</span></>}</div><div className={`${wide ? "flex flex-col justify-center" : ""} p-7 md:p-9`}><p className="text-xs font-semibold uppercase tracking-[.1em] text-ink/40">{label}</p><h3 className="mt-4 text-2xl font-semibold tracking-[-.03em] text-ink md:text-3xl">{title}</h3><span className="mt-7 inline-block text-sm text-ink/50 transition-transform group-hover:translate-x-1">View project →</span></div></Link>; }
