import Link from "next/link";

type SolutionDetailProps = { eyebrow: string; title: string; intro: string; outcomes: readonly { title: string; text: string }[]; workflow: readonly string[] };

export function SolutionDetail({ eyebrow, title, intro, outcomes, workflow }: SolutionDetailProps) {
  const customerAgent = eyebrow === "AI Customer Agent";
  return <>
    <section className="page-hero-grid relative overflow-hidden border-b border-ink/10 py-20 md:py-28"><div className="page-glow absolute inset-y-0 right-0 w-1/2" /><div className="container-site relative grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-7 max-w-4xl font-serif text-[clamp(3.5rem,6.4vw,6.5rem)] leading-[.9] tracking-[-.045em] text-ink">{title}</h1><p className="mt-8 max-w-xl text-base leading-8 text-ink/58">{intro}</p><Link href="/get-started" className="mt-8 inline-flex bg-ink px-6 py-4 text-sm text-ivory transition-transform hover:-translate-y-0.5">Discuss your process →</Link></div><EvidencePanel customerAgent={customerAgent} /></div></section>
    <section className="relative overflow-hidden bg-ink py-20 text-ivory"><div className="absolute inset-0 technical-grid-dark opacity-30" /><div className="container-site relative"><div className="flex items-end justify-between border-b border-white/15 pb-7"><div><p className="text-[.6rem] uppercase tracking-[.2em] text-gold">How it moves</p><h2 className="mt-4 font-serif text-4xl">One connected workflow.</h2></div><span className="hidden font-mono text-[.5rem] text-white/25 md:block">SYSTEM / 01</span></div><div className="mt-8 grid md:grid-cols-3 lg:grid-cols-6">{workflow.map((step, index) => <div key={step} className="group relative min-h-44 border-l border-white/15 p-5 transition-colors hover:bg-white/[.04]"><span className="font-mono text-[.5rem] text-gold">0{index + 1}</span><p className="mt-14 font-serif text-2xl">{step}</p>{index < workflow.length - 1 ? <span className="absolute -right-2 top-1/2 z-10 hidden size-4 place-items-center bg-gold text-[.5rem] text-ink lg:grid">→</span> : null}</div>)}</div></div></section>
    <section className="py-24 md:py-32"><div className="container-site"><div className="grid gap-8 border-b border-ink/15 pb-10 md:grid-cols-2"><h2 className="font-serif text-5xl tracking-[-.035em] text-ink">Built around the work.</h2><p className="max-w-lg text-sm leading-7 text-ink/55">The system is defined around the decisions, handoffs and information the business actually needs.</p></div><div className="grid md:grid-cols-2">{outcomes.map((item, index) => <article key={item.title} className="group relative min-h-72 overflow-hidden border-b border-r border-ink/10 p-7 transition-colors hover:bg-brand-stone/25"><span className="font-mono text-[.5rem] text-gold">0{index + 1}</span><div className="absolute right-7 top-7 size-10 border border-ink/10 transition-transform group-hover:rotate-45" /><h3 className="mt-16 font-serif text-3xl text-ink">{item.title}</h3><p className="mt-4 max-w-md text-sm leading-7 text-ink/52">{item.text}</p></article>)}</div></div></section>
  </>;
}

function EvidencePanel({ customerAgent }: { customerAgent: boolean }) {
  if (customerAgent) return <div className="evidence-frame relative min-h-[34rem] border border-ink/15 bg-[#f4f0e8] p-4 shadow-[0_30px_70px_rgba(13,27,42,.14)]"><div className="flex h-10 items-center justify-between border-b border-ink/10 px-3 text-[.5rem] uppercase tracking-[.15em] text-ink/40"><span>Meleph Agent</span><span className="flex items-center gap-2"><i className="size-1.5 rounded-full bg-[#5c8a6c]" />Active</span></div><div className="grid h-[27rem] grid-cols-[8rem_1fr]"><div className="bg-ink p-3 text-white"><p className="text-[.48rem] uppercase tracking-wider text-white/35">Inbox</p>{["Enterprise enquiry", "Pricing question", "Book a visit"].map((item, i) => <div key={item} className={`mt-3 border-l-2 p-2 text-[.52rem] ${i === 0 ? "border-gold bg-white/10" : "border-transparent text-white/45"}`}>{item}</div>)}</div><div className="flex flex-col p-4"><div className="border-b border-ink/10 pb-3"><p className="text-[.58rem] font-semibold text-ink">Active conversation</p><p className="text-[.45rem] text-ink/35">Context captured as the conversation develops</p></div><div className="mt-5 max-w-[82%] border border-ink/10 bg-white p-3 text-[.54rem] leading-5 text-ink/60">We are looking for an enterprise package for a team of around 75.</div><div className="ml-auto mt-3 max-w-[85%] bg-ink p-3 text-[.54rem] leading-5 text-white/75">I can help with that. I&apos;ll capture your requirements and connect you with the right person.</div><div className="mt-auto grid grid-cols-2 gap-2"><MiniField label="Intent" value="Enterprise enquiry" /><MiniField label="Next action" value="Schedule consultation" /></div></div></div><div className="absolute -bottom-5 -right-5 border border-ink/15 bg-ivory px-4 py-3 shadow-lg"><p className="text-[.45rem] uppercase tracking-wider text-ink/35">Handoff ready</p><p className="mt-1 text-[.58rem] font-semibold text-ink">Context + contact captured</p></div></div>;
  return <div className="evidence-frame relative min-h-[34rem] border border-ink/15 bg-ink p-5 text-white shadow-[0_30px_70px_rgba(13,27,42,.18)]"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div><p className="text-[.5rem] uppercase tracking-[.16em] text-gold">Operations workspace</p><p className="mt-1 text-[.46rem] text-white/30">Connected workflow</p></div><span className="font-mono text-[.5rem] text-white/30">LIVE</span></div><div className="mt-6 grid grid-cols-[1fr_.72fr] gap-3"><div className="border border-white/10 p-4"><p className="text-[.48rem] uppercase tracking-wider text-white/35">Work queue</p>{[["New request", "Captured"], ["Review context", "Assigned"], ["Approve action", "Pending"], ["Update system", "Ready"]].map(([task, state], i) => <div key={task} className="mt-3 flex items-center border-b border-white/8 pb-3 text-[.52rem]"><span className={`mr-2 size-1.5 rounded-full ${i < 2 ? "bg-[#6b9b79]" : "bg-gold"}`} /><span>{task}</span><span className="ml-auto text-white/30">{state}</span></div>)}</div><div className="space-y-3"><div className="border border-white/10 p-4"><p className="text-[.45rem] uppercase tracking-wider text-white/35">Knowledge</p><p className="mt-6 font-serif text-3xl text-gold">Connected</p></div><div className="border border-white/10 p-4"><p className="text-[.45rem] uppercase tracking-wider text-white/35">Team view</p><div className="mt-5 flex gap-1">{[1,2,3,4].map(i => <i key={i} className="h-12 flex-1 bg-white/[.06]" style={{ marginTop: `${(4-i)*5}px` }} />)}</div></div></div></div><div className="mt-3 border border-white/10 p-4"><div className="flex justify-between text-[.48rem] text-white/35"><span>INPUT</span><span>DECISION</span><span>ACTION</span><span>RECORD</span></div><div className="relative mt-4 h-px bg-white/15"><i className="absolute left-0 top-1/2 size-2 -translate-y-1/2 rounded-full bg-gold" /><i className="absolute left-1/3 top-1/2 size-2 -translate-y-1/2 rounded-full bg-gold" /><i className="absolute left-2/3 top-1/2 size-2 -translate-y-1/2 rounded-full bg-gold" /><i className="absolute right-0 top-1/2 size-2 -translate-y-1/2 rounded-full bg-gold" /></div></div></div>;
}

function MiniField({ label, value }: { label: string; value: string }) { return <div className="border border-ink/10 bg-white p-2.5"><p className="text-[.42rem] uppercase tracking-wider text-ink/35">{label}</p><p className="mt-1 text-[.52rem] font-medium text-ink">{value}</p></div>; }
